// Generated by gencpp from file pocky_vision/pocky_dataRequest.msg
// DO NOT EDIT!


#ifndef POCKY_VISION_MESSAGE_POCKY_DATAREQUEST_H
#define POCKY_VISION_MESSAGE_POCKY_DATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pocky_vision
{
template <class ContainerAllocator>
struct pocky_dataRequest_
{
  typedef pocky_dataRequest_<ContainerAllocator> Type;

  pocky_dataRequest_()
    : request_flag(0)  {
    }
  pocky_dataRequest_(const ContainerAllocator& _alloc)
    : request_flag(0)  {
  (void)_alloc;
    }



   typedef int64_t _request_flag_type;
  _request_flag_type request_flag;





  typedef boost::shared_ptr< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pocky_dataRequest_

typedef ::pocky_vision::pocky_dataRequest_<std::allocator<void> > pocky_dataRequest;

typedef boost::shared_ptr< ::pocky_vision::pocky_dataRequest > pocky_dataRequestPtr;
typedef boost::shared_ptr< ::pocky_vision::pocky_dataRequest const> pocky_dataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pocky_vision::pocky_dataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pocky_vision::pocky_dataRequest_<ContainerAllocator1> & lhs, const ::pocky_vision::pocky_dataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request_flag == rhs.request_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pocky_vision::pocky_dataRequest_<ContainerAllocator1> & lhs, const ::pocky_vision::pocky_dataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pocky_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68a61dd9374748e7d9ec4f21de7be8ea";
  }

  static const char* value(const ::pocky_vision::pocky_dataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68a61dd9374748e7ULL;
  static const uint64_t static_value2 = 0xd9ec4f21de7be8eaULL;
};

template<class ContainerAllocator>
struct DataType< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pocky_vision/pocky_dataRequest";
  }

  static const char* value(const ::pocky_vision::pocky_dataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64   request_flag\n"
;
  }

  static const char* value(const ::pocky_vision::pocky_dataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pocky_dataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pocky_vision::pocky_dataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pocky_vision::pocky_dataRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_flag: ";
    Printer<int64_t>::stream(s, indent + "  ", v.request_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POCKY_VISION_MESSAGE_POCKY_DATAREQUEST_H
