// Generated by gencpp from file pocky_vision/pocky_data.msg
// DO NOT EDIT!


#ifndef POCKY_VISION_MESSAGE_POCKY_DATA_H
#define POCKY_VISION_MESSAGE_POCKY_DATA_H

#include <ros/service_traits.h>


#include <pocky_vision/pocky_dataRequest.h>
#include <pocky_vision/pocky_dataResponse.h>


namespace pocky_vision
{

struct pocky_data
{

typedef pocky_dataRequest Request;
typedef pocky_dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pocky_data
} // namespace pocky_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pocky_vision::pocky_data > {
  static const char* value()
  {
    return "4482c320afdc1319d32f82f385f7708d";
  }

  static const char* value(const ::pocky_vision::pocky_data&) { return value(); }
};

template<>
struct DataType< ::pocky_vision::pocky_data > {
  static const char* value()
  {
    return "pocky_vision/pocky_data";
  }

  static const char* value(const ::pocky_vision::pocky_data&) { return value(); }
};


// service_traits::MD5Sum< ::pocky_vision::pocky_dataRequest> should match
// service_traits::MD5Sum< ::pocky_vision::pocky_data >
template<>
struct MD5Sum< ::pocky_vision::pocky_dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pocky_vision::pocky_data >::value();
  }
  static const char* value(const ::pocky_vision::pocky_dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pocky_vision::pocky_dataRequest> should match
// service_traits::DataType< ::pocky_vision::pocky_data >
template<>
struct DataType< ::pocky_vision::pocky_dataRequest>
{
  static const char* value()
  {
    return DataType< ::pocky_vision::pocky_data >::value();
  }
  static const char* value(const ::pocky_vision::pocky_dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pocky_vision::pocky_dataResponse> should match
// service_traits::MD5Sum< ::pocky_vision::pocky_data >
template<>
struct MD5Sum< ::pocky_vision::pocky_dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pocky_vision::pocky_data >::value();
  }
  static const char* value(const ::pocky_vision::pocky_dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pocky_vision::pocky_dataResponse> should match
// service_traits::DataType< ::pocky_vision::pocky_data >
template<>
struct DataType< ::pocky_vision::pocky_dataResponse>
{
  static const char* value()
  {
    return DataType< ::pocky_vision::pocky_data >::value();
  }
  static const char* value(const ::pocky_vision::pocky_dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POCKY_VISION_MESSAGE_POCKY_DATA_H
