// Generated by gencpp from file pocky_vision/vision_state.msg
// DO NOT EDIT!


#ifndef POCKY_VISION_MESSAGE_VISION_STATE_H
#define POCKY_VISION_MESSAGE_VISION_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pocky_vision
{
template <class ContainerAllocator>
struct vision_state_
{
  typedef vision_state_<ContainerAllocator> Type;

  vision_state_()
    : state(0)  {
    }
  vision_state_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef int64_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::pocky_vision::vision_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pocky_vision::vision_state_<ContainerAllocator> const> ConstPtr;

}; // struct vision_state_

typedef ::pocky_vision::vision_state_<std::allocator<void> > vision_state;

typedef boost::shared_ptr< ::pocky_vision::vision_state > vision_statePtr;
typedef boost::shared_ptr< ::pocky_vision::vision_state const> vision_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pocky_vision::vision_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pocky_vision::vision_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pocky_vision::vision_state_<ContainerAllocator1> & lhs, const ::pocky_vision::vision_state_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pocky_vision::vision_state_<ContainerAllocator1> & lhs, const ::pocky_vision::vision_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pocky_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pocky_vision::vision_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pocky_vision::vision_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pocky_vision::vision_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pocky_vision::vision_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pocky_vision::vision_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pocky_vision::vision_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pocky_vision::vision_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "979940cbf4c11dcaa39d4ce8683ecc86";
  }

  static const char* value(const ::pocky_vision::vision_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x979940cbf4c11dcaULL;
  static const uint64_t static_value2 = 0xa39d4ce8683ecc86ULL;
};

template<class ContainerAllocator>
struct DataType< ::pocky_vision::vision_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pocky_vision/vision_state";
  }

  static const char* value(const ::pocky_vision::vision_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pocky_vision::vision_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 state  \n"
;
  }

  static const char* value(const ::pocky_vision::vision_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pocky_vision::vision_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vision_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pocky_vision::vision_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pocky_vision::vision_state_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POCKY_VISION_MESSAGE_VISION_STATE_H
