# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pocky_vision/ROI_top.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ROI_top(genpy.Message):
  _md5sum = "3d377af5cd089c7785cff2ae8dcde5c3"
  _type = "pocky_vision/ROI_top"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string  top_box
float64 top_CenterX
float64 top_CenterY
float64 top_Angle"""
  __slots__ = ['top_box','top_CenterX','top_CenterY','top_Angle']
  _slot_types = ['string','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       top_box,top_CenterX,top_CenterY,top_Angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ROI_top, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.top_box is None:
        self.top_box = ''
      if self.top_CenterX is None:
        self.top_CenterX = 0.
      if self.top_CenterY is None:
        self.top_CenterY = 0.
      if self.top_Angle is None:
        self.top_Angle = 0.
    else:
      self.top_box = ''
      self.top_CenterX = 0.
      self.top_CenterY = 0.
      self.top_Angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.top_box
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.top_CenterX, _x.top_CenterY, _x.top_Angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.top_box = str[start:end].decode('utf-8')
      else:
        self.top_box = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.top_CenterX, _x.top_CenterY, _x.top_Angle,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.top_box
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.top_CenterX, _x.top_CenterY, _x.top_Angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.top_box = str[start:end].decode('utf-8')
      else:
        self.top_box = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.top_CenterX, _x.top_CenterY, _x.top_Angle,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
