# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pocky_vision/ROI_array_top.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import pocky_vision.msg

class ROI_array_top(genpy.Message):
  _md5sum = "355919cc8ce59f1f4229b0fb075cd563"
  _type = "pocky_vision/ROI_array_top"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """ROI_top[] ROI_top_list

================================================================================
MSG: pocky_vision/ROI_top
string  top_box
float64 top_CenterX
float64 top_CenterY
float64 top_Angle"""
  __slots__ = ['ROI_top_list']
  _slot_types = ['pocky_vision/ROI_top[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ROI_top_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ROI_array_top, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ROI_top_list is None:
        self.ROI_top_list = []
    else:
      self.ROI_top_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.ROI_top_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.ROI_top_list:
        _x = val1.top_box
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_3d().pack(_x.top_CenterX, _x.top_CenterY, _x.top_Angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ROI_top_list is None:
        self.ROI_top_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ROI_top_list = []
      for i in range(0, length):
        val1 = pocky_vision.msg.ROI_top()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.top_box = str[start:end].decode('utf-8')
        else:
          val1.top_box = str[start:end]
        _x = val1
        start = end
        end += 24
        (_x.top_CenterX, _x.top_CenterY, _x.top_Angle,) = _get_struct_3d().unpack(str[start:end])
        self.ROI_top_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.ROI_top_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.ROI_top_list:
        _x = val1.top_box
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_3d().pack(_x.top_CenterX, _x.top_CenterY, _x.top_Angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ROI_top_list is None:
        self.ROI_top_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ROI_top_list = []
      for i in range(0, length):
        val1 = pocky_vision.msg.ROI_top()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.top_box = str[start:end].decode('utf-8')
        else:
          val1.top_box = str[start:end]
        _x = val1
        start = end
        end += 24
        (_x.top_CenterX, _x.top_CenterY, _x.top_Angle,) = _get_struct_3d().unpack(str[start:end])
        self.ROI_top_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
